export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const REGISTER_SUCCESS ="REGISTER_SUCCESS"
export const LOGOUT = "LOGOUT"
export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"